server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 2MB
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${db.host}:3306/online_judge?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${db.password}

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
  mapper-locations: classpath*:/com/chenru1chao/mapper/*.xml

test-case:
  file-path:
    prefix: ${test-case.file-path.prefix}

oj:
  jwt:
    key: ${oj.jwt.key}
    ttl: ${oj.jwt.ttl}
    token-name: ${oj.jwt.token-name}
  alioss:
    access-key-id: ${oj.alioss.access-key-id}
    access-key-secret: ${oj.alioss.access-key-secret}
    bucket-name: ${oj.alioss.bucket-name}
    endpoint: ${oj.alioss.endpoint}
    max-size-mb: 2
    allowed-extensions: "jpg,png"